# ─── Configuración de ms-admin-api-gateway ────────────────────────────────
server.port=8080

spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.mvc.routes[1].id=ms-gestion-instructor
spring.cloud.gateway.mvc.routes[1].uri=lb://ms-gestion-instructor
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/instructores/**

spring.cloud.gateway.mvc.routes[2].id=ms-gestion-alumno
spring.cloud.gateway.mvc.routes[2].uri=lb://ms-gestion-alumno
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/alumnos/**

spring.cloud.gateway.mvc.routes[3].id=ms-gestion-taller
spring.cloud.gateway.mvc.routes[3].uri=lb://ms-gestion-taller
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/talleres/**

management.endpoints.web.exposure.include=health,info,gateway
